export interface CaseStudy {
  id: string;
  company: string;
  industry: string;
  tagline: string;
  description: string;
  challenge: string;
  solution: string;
  results: {
    metric: string;
    description: string;
  }[];
  systems: string[];
  testimonial: string;
  image: string;
}

export const caseStudies: CaseStudy[] = [
  {
    id: "bacho-iliya",
    company: "Бачо Илия",
    industry: "Млечна индустрия",
    tagline:
      "Mарка с обичан вкус и богата история, но без изградена дигитална връзка със своите потребители и търговски партньори.",
    description:
      "Традиционен млечен производител с богата история, който се нуждаеше от модерна дигитална присъствие за достигане до нови аудитории.",
    challenge:
      "Компанията разчиташе основно на традиционни канали за продажба и имаше слаба онлайн видимост. Нуждаеше се от система за изграждане на бранд авторитет и привличане на по-млада аудитория.",
    solution:
      "Първо внедрихме Trendlab™ система, която създаде стратегия за носталгия и доверие, базирана на богатата история на бранда. След това произведохме над 100 видео публикации месечно, разказващи автентични истории. Накрая активирахме Clientomat™ за разпространение на съдържанието до 5 милиона гледания месечно с минимален рекламен бюджет.",
    results: [
      {
        metric: "5 000 000",
        description: "гледания на месец с минимален бюджет",
      },
      { metric: "+243%", description: "ръст на месечната бранд аудитория" },
      { metric: "70%", description: "ръст на запитванията от дистрибутори" },
    ],
    systems: ["Trendlab™", "Clientomat™"],
    testimonial:
      "Pravdast ни помогна да превърнем традиционния ни бизнес в модерен бранд, без да загубим автентичността си.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "euphoria-beauty",
    company: "Euphoria Beauty",
    industry: "Козметични услуги",
    tagline: "Салон с репутация. Без дигитална визия.",
    description:
      "Успешен козметичен салон във Варна с отлична репутация сред съществуващите клиенти, но липса на онлайн присъствие.",
    challenge:
      "Салонът разчиташе изцяло на препоръки от уста на уста и нямаше видимост в Google. Нуждаеше се от локална SEO стратегия и система за привличане на нови клиенти.",
    solution:
      "Внедрихме SEO Struktor™ система, фокусирана върху локални търсения. Оптимизирахме Google My Business профила и създадохме съдържание, насочено към местната аудитория във Варна.",
    results: [
      { metric: "+280%", description: "повече запитвания онлайн" },
      { metric: "+137%", description: "нови клиенти от Google" },
      { metric: "+42%", description: "разпознаваемост на бранд" },
    ],
    systems: ["SEO Struktor™", "Clientomat™"],
    testimonial:
      "Благодарение на Pravdast сега имаме постоянен поток от нови клиенти.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "ice-tub-co",
    company: "Ice Tub Co.",
    industry: "Фитнес оборудване",
    tagline: "От нулева SEO стратегия до 1.1M оборот.",
    description:
      "Британска компания за ледени вани, която търсеше систематичен подход за навлизане на европейския пазар.",
    challenge:
      "Компанията имаше качествен продукт, но нямаше онлайн видимост в Европа. Нуждаеше се от цялостна дигитална стратегия за навлизане на нови пазари.",
    solution:
      "Внедрихме комбинация от SEO Struktor™ за органична видимост, Clickstarter™ за оптимизация на рекламите и Clientomat™ за автоматизация на продажбения процес.",
    results: [
      { metric: "13.9K", description: "месечни посещения (от 2.3K)" },
      { metric: "£1.5M", description: "месечен приход (от £400K)" },
      { metric: "+27%", description: "поръчки с Clientomat™" },
    ],
    systems: ["SEO Struktor™", "Clickstarter™", "Clientomat™"],
    testimonial:
      "Pravdast ни помогна да изградим предсказуема система за растеж. Резултатите превъзхождат очакванията ни.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "dejavu-gym",
    company: "DeJaVu Gym",
    industry: "Фитнес",
    tagline: "Популярен фитнес. Никаква система.",
    description:
      "Установен фитнес център с лоялни членове, но без система за привличане на нови клиенти и задържане на съществуващите.",
    challenge:
      "Фитнес центърът разчиташе на случайни записвания и нямаше структуриран подход за задържане на клиентите. Нуждаеше се от система за увеличаване на лоялността и препоръките.",
    solution:
      "Внедрихме Clientomat™ за автоматизация на клиентския жизнен цикъл и Trendlab™ за изграждане на силна общност около бранда.",
    results: [
      { metric: "+41%", description: "повече активни абонаменти" },
      { metric: "+66%", description: "повече препоръки" },
      {
        metric: "53.13%",
        description: "96,000 лв. → 147,000 лв. ръст на оборота",
      },
    ],
    systems: ["Clientomat™", "Trendlab™"],
    testimonial:
      "Сега имаме ясна система, която работи автоматично. Членовете остават по-дълго и препоръчват повече приятели.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "the-key-beer-bar",
    company: "The Key Beer Bar",
    industry: "Ресторантьорство",
    tagline: "Бира бар с уникален характер, но прекалено зависим от доставки на трети страни.",
    description: "The Key Beer Bar правеха 1050 поръчки месечно чрез Glovo на средна стойност 30 лв. Всеки месец плащаха 9450 лв комисионни - повече от половината от оборота си.",
    challenge: "The Key Beer Bar правеха 1050 поръчки месечно чрез Glovo на средна стойност 30 лв. Всеки месец плащаха 9450 лв комисионни - повече от половината от оборота си. Имаха лоялни клиенти, но Glovo притежаваше връзката с тях. Нямаха система за директно взаимодействие с клиентската си база.",
    solution: "Внедрихме тристепенна стратегия за директни поръчки. Първо създадохме привлекателна система за лоялност с 10% отстъпка за директни поръчки. След това оптимизирахме доставката им до 25 минути - по-бързо от Glovo. Накрая активирахме персонализирана комуникация с всеки клиент чрез директен телефон и лично отношение.",
    results: [
      { metric: "70%", description: "намаление на Glovo комисионни" },
      { metric: "6,615 лв", description: "месечно спестени средства" },
      { metric: "79,380 лв", description: "годишно - възвръщане на инвестицията" },
      { metric: "25 мин", description: "средно време за доставка (по-бързо от Glovo)" },
    ],
    systems: ["Clickstarter™", "Clientomat™"],
    testimonial: "За 3 месеца спестихме повече пари, отколкото сме инвестирали в барът за цяла година. Сега клиентите са НАШИ, не на Glovo.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "rosa-doro-pizza",
    company: "Rosa D'Oro Pizza",
    industry: "Ресторантьорство",
    tagline: "Автентична италианска пицария с две локации, но с ограничен контрол над клиентската база.",
    description: "Златко и Ники от Rosa D'Oro правеха 1500 поръчки месечно чрез Glovo по 43 лв средно. Всеки месец хвърляха 19,350 лв в комисионни.",
    challenge: "Златко и Ники от Rosa D'Oro правеха 1500 поръчки месечно чрез Glovo по 43 лв средно. Всеки месец хвърляха 19,350 лв в комисионни. Въпреки отличното качество на храната и автентичните италиански рецепти, нямаха пряка връзка с клиентите си. Glovo контролираше цялата им онлайн присъствие.",
    solution: "Създадохме система за 'Пица парти' с предварително планиране и фиксиран час на доставка. Внедрихме лоялностна програма с персонализирани оферти за всеки клиент. Разработихме собствена платформа за поръчки, която се интегрира с техните две локации - зад Катедралата и в кв. Възраждане.",
    results: [
      { metric: "70%", description: "редукция на зависимостта от Glovo" },
      { metric: "13,545 лв", description: "месечно пестене" },
      { metric: "162,540 лв", description: "годишна икономия" },
      { metric: "1050", description: "директни поръчки спрямо 450 през Glovo" },
    ],
    systems: ["Clickstarter™", "Clientomat™"],
    testimonial: "Преди Glovo ни контролираше. Сега ние контролираме нашия бизнес. Клиентите обичат директното общуване и бързите доставки.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "best-burgers-varna",
    company: "Best Burgers Varna",
    industry: "Ресторантьорство",
    tagline: "Най-вкусните бургери във Варна с отлична репутация, но ограничени от високи комисионни.",
    description: "Best Burgers с техните веган, вегетариански и месни опции правеха 450 поръчки месечно чрез Glovo по 30 лв. Плащаха 4,050 лв месечно комисионни въпреки перфектните отзиви от клиентите.",
    challenge: "Best Burgers с техните веган, вегетариански и месни опции правеха 450 поръчки месечно чрез Glovo по 30 лв. Плащаха 4,050 лв месечно комисионни въпреки перфектните отзиви от клиентите. Имаха две локации - на бул. Сливница и в Тракия, но нямаха ефективна система за директни поръчки.",
    solution: "Разработихме система за бързи поръчки по телефон с девиза 'поръчай и вземи без да чакаш'. Създадохме меню специално за директни клиенти с ексклузивни комбинации. Внедрихме SMS система за уведомяване на готовността на поръчката в реално време.",
    results: [
      { metric: "70%", description: "намаление на Glovo зависимост" },
      { metric: "2,835 лв", description: "месечно пестене" },
      { metric: "34,020 лв", description: "годишна икономия" },
      { metric: "90%", description: "успешност на директната телефонна линия" },
    ],
    systems: ["Clickstarter™", "Clientomat™"],
    testimonial: "Нашите клиенти винаги са казвали, че правим най-добрите бургери във Варна. Сега и печалбата ни отразява това качество.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "atelier-60",
    company: "Atelier 60",
    industry: "Ресторантьорство",
    tagline: "Premium ресторант с модерна кухня, блокиран от intermediary platforms.",
    description: "Atelier 60 позиционираха себе си като premium дестинация с деликатни суши купи, специални смути и изисканото меню. При 240 поръчки месечно от 30 лв, отдаваха 2,160 лв на Glovo.",
    challenge: "Atelier 60 позиционираха себе си като premium дестинация с деликатни суши купи, специални смути и изисканото меню. При 240 поръчки месечно от 30 лв, отдаваха 2,160 лв на Glovo - пари които можеха да инвестират в още по-качествени съставки. Техните клиенти плащаха за premium преживяване, но 30% от стойността отиваше при посредника.",
    solution: "Разработихме 'Atelier Circle' - ексклузивен клуб за премиум клиенти с достъп до limited edition ястия. Внедрихме персонален chef advisor по WhatsApp за диетични съвети и препоръки. Създадохме weekly tasting меню достъпно само за директни клиенти с предварителна резервация.",
    results: [
      { metric: "60%", description: "reduction в platform dependency" },
      { metric: "1,300 лв", description: "месечни спестявания" },
      { metric: "15,600 лв", description: "годишна печалба" },
      { metric: "+35%", description: "увеличение в средната стойност на поръчка" },
    ],
    systems: ["Clickstarter™", "Clientomat™"],
    testimonial: "Нашите клиенти търсят не просто храна, а culinary experience. Директната връзка ни позволява да им дадем точно това.",
    image: "/api/placeholder/600/400",
  },
  // FOOD SUPPLEMENTS CATEGORY - GERMANY
  {
    id: "biovital-hamburg",
    company: "BioVital Hamburg",
    industry: "Хранителни добавки",
    tagline: "Германска компания за органични спортни добавки с фокус върху натуралните съставки.",
    description: "Водещ производител на органични спортни добавки в северна Германия с 15-годишна история и фокус върху чистите, натурални продукти.",
    challenge: "Компанията имаше отлично качество на продуктите, но слаба онлайн видимост на немския пазар. Конкуренцията от големи брандове затрудняваше достигането до target аудиторията от фитнес ентусиасти.",
    solution: "Внедрихме SEO Struktor™ система за немския пазар, оптимизирана за термини като 'Bio Protein', 'natürliche Supplements' и 'organische Sportnahrung'. Създадохме съдържание за растителни алтернативи и Clientomat™ за автоматизация на client journey.",
    results: [
      { metric: "+340%", description: "органичен трафик за 8 месеца" },
      { metric: "+180%", description: "онлайн продажби" },
      { metric: "€125,000", description: "допълнителен месечен оборот" },
      { metric: "+65%", description: "email списък от нови абонати" },
    ],
    systems: ["SEO Struktor™", "Clientomat™"],
    testimonial: "Благодарение на Pravdast успяхме да се наложим на немския пазар срещу големите корпорации. Органичният трафик ни донесе нови клиенти всеки ден.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "nutrimax-berlin",
    company: "NutriMax Berlin",
    industry: "Хранителни добавки",
    tagline: "Веган протеини и аминокиселини за съвременните берлинци.",
    description: "Специалист по растителни протеини и веган добавки, обслужващ rapidly growing веган общността в Берлин.",
    challenge: "Нишовият пазар на веган добавки беше силно фрагментиран. Компанията се бореше да достигне до правилната аудитория и да изгради доверие сред веган спортистите в германоезичния регион.",
    solution: "Разработихме Trendlab™ стратегия, фокусирана върху веган lifestyle тенденциите. Внедрихме Clickstarter™ за targeted реклами в социалните мрежи и SEO Struktor™ за органична видимост при търсения за 'vegane Proteine' и 'pflanzliche Aminosäuren'.",
    results: [
      { metric: "+250%", description: "conversion rate от веган общности" },
      { metric: "€95,000", description: "месечни продажби (от €28,000)" },
      { metric: "+420%", description: "социални медии engagement" },
      { metric: "75%", description: "клиенти с повторни покупки" },
    ],
    systems: ["Trendlab™", "Clickstarter™", "SEO Struktor™"],
    testimonial: "Pravdast ни помогна да станем #1 веган протеинов бранд в Берлин. Сега имаме лист за чакане за някои продукти!",
    image: "/api/placeholder/600/400",
  },
  {
    id: "supplementexpert-munchen",
    company: "SupplementExpert München",
    industry: "Хранителни добавки",
    tagline: "Онлайн магазин за фитнес добавки с focus върху German quality standards.",
    description: "Премиум онлайн дистрибутор на фитнес добавки в Бавария, специализиран в imported американски брандове и European alternatives.",
    challenge: "Онлайн competition за фитнес добавки в Германия беше изключително агресивна. Компанията имаше проблем с customer acquisition cost и difficulty establishing авторитет срещу established retailers.",
    solution: "Активирахме комбинация от всичките ни системи. SEO Struktor™ за long-tail keywords, Trendlab™ за fitness trend съдържание, Clickstarter™ за paid ads optimization и Clientomat™ за customer retention и automated upselling.",
    results: [
      { metric: "€280,000", description: "месечен оборот (от €85,000)" },
      { metric: "+195%", description: "средна стойност на поръчка" },
      { metric: "-60%", description: "customer acquisition cost" },
      { metric: "+155%", description: "repeat purchase rate" },
    ],
    systems: ["SEO Struktor™", "Trendlab™", "Clickstarter™", "Clientomat™"],
    testimonial: "Mit Pravdast haben wir den deutschen Fitness-Supplement-Markt erobert. Unsere Kunden kommen jetzt zu uns!",
    image: "/api/placeholder/600/400",
  },
  {
    id: "germanhealth-koln",
    company: "GermanHealth Köln",
    industry: "Хранителни добавки", 
    tagline: "Витамини и минерали за възрастни с Focus върху имунитета.",
    description: "Семейна компания в Кьолн, специализирана в витамини за възрастни 50+ и имуностимулиращи добавки с натурални германски съставки.",
    challenge: "Aging population в Германия създаваше голям пазар, но компанията нямаше digital presence. Target аудиторията от възрастни хора беше трудна за достигане online.",
    solution: "Създадохме educational content strategy чрез Trendlab™, фокусирана върху здравето в зряла възраст. SEO Struktor™ за medical-related searches и Clientomat™ за gentle, trust-building customer journey подходящ за 50+ демографията.",
    results: [
      { metric: "+180%", description: "уеб посещения от target група" },
      { metric: "€75,000", description: "месечни продажби (от €32,000)" },
      { metric: "+90%", description: "email engagement rate" },
      { metric: "4.8/5", description: "customer satisfaction score" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Endlich erreichen wir unsere Zielgruppe online. Die älteren Kunden vertrauen uns mehr denn je.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "powerboost-dresden",
    company: "PowerBoost Dresden",
    industry: "Хранителни добавки",
    tagline: "Pre-workout и енергийни добавки за high-performance атлети.",
    description: "Innovative startup в Дрезден, focused на cutting-edge pre-workout формули и енергийни бустери за профessionални и amateur атлети.",
    challenge: "Saturated pre-workout market с aggressive competition от international брандове. Startup needed да establish credibility и научи как да compete срещу million-dollar advertising budgets.",
    solution: "Приложихме agile approach с Trendlab™ за viral fitness content, Clickstarter™ за cost-effective performance marketing, и SEO Struktor™ за authority building чрез scientific content за workout performance.",
    results: [
      { metric: "+450%", description: "бранд awareness в East Germany" },
      { metric: "€140,000", description: "месечни продажби (от €25,000)" },
      { metric: "+300%", description: "influencer partnerships" },
      { metric: "85%", description: "customer retention rate" },
    ],
    systems: ["Trendlab™", "Clickstarter™", "SEO Struktor™"],
    testimonial: "Von Startup zu Market Leader in Ostdeutschland - Pravdast machte es möglich!",
    image: "/api/placeholder/600/400",
  },
  // FOOD SUPPLEMENTS CATEGORY - UK
  {
    id: "healthylife-london",
    company: "HealthyLife London",
    industry: "Хранителни добавки",
    tagline: "Натурални добавки за жени с focus върху hormonal balance.",
    description: "London-based компания специализирана в women's health supplements, включително hormonal support, prenatal витамини и beauty supplements.",
    challenge: "Women's health е sensitive topic изискващ доверие и expertise. Компанията се бореше да establish authority в crowded UK wellness market и да navigate строги health claim regulations.",
    solution: "Разработихме science-based content strategy чрез Trendlab™, включваща collaboration с женски health experts. SEO Struktor™ за medical-compliant keywords и Clientomat™ за personalized recommendations based на life stage и health goals.",
    results: [
      { metric: "+280%", description: "qualified leads от women 25-45" },
      { metric: "£95,000", description: "месечни продажби (от £34,000)" },
      { metric: "+160%", description: "email list growth" },
      { metric: "92%", description: "customer satisfaction rate" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Finally, we're reaching women who truly need our products. Our expertise is now visible online.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "supremefit-manchester",
    company: "SupremeFit Manchester",
    industry: "Хранителни добавки",
    tagline: "Спортни добавки за мъже с emphasis върху силата и мускулната маса.",
    description: "Established Manchester-based retailer на спортни добавки, catering към strength training community в Северна Англия.",
    challenge: "Local competition от големи fitness chains и онлайн retailers. Нужда от differentiation и stronger online presence за да compete ефективно.",
    solution: "Внедрихме local SEO strategy чрез SEO Struktor™ combined с community building чрез Trendlab™. Clickstarter™ за geo-targeted рeklami и Clientomat™ за loyalty programs focused на Manchester fitness community.",
    results: [
      { metric: "+210%", description: "local search visibility" },
      { metric: "£78,000", description: "месечни продажби (от £36,000)" },
      { metric: "+135%", description: "в-магазин посещения" },
      { metric: "68%", description: "local market share" },
    ],
    systems: ["SEO Struktor™", "Trendlab™", "Clickstarter™", "Clientomat™"],
    testimonial: "We've become THE go-to supplement shop in Manchester. Local gyms recommend us to their members!",
    image: "/api/placeholder/600/400",
  },
  {
    id: "vitaminpro-birmingham",
    company: "VitaminPro Birmingham",
    industry: "Хранителни добавки",
    tagline: "Детски витамини и имуностимулиращи добавки за families.",
    description: "Family-focused supplement shop в Birmingham, специализирана в детски витамини, имунна подкрепа и family wellness products.",
    challenge: "Parents са изключително careful когато става дума за детски supplements. Трябваше да изградим extreme trust и да educate parents за benefits of supplementation.",
    solution: "Създадохме parent education program чрез Trendlab™ с pediatric nutritionist content. SEO Struktor™ за parenting-related health searches и Clientomat™ за seasonal wellness campaigns и family-focused recommendations.",
    results: [
      { metric: "+190%", description: "parent engagement и trust" },
      { metric: "£65,000", description: "месечни продажби (от £28,000)" },
      { metric: "+240%", description: "seasonal supplement sales" },
      { metric: "4.9/5", description: "parent satisfaction rating" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Parents trust us with their children's health. That's the highest compliment we could receive.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "nutribest-leeds",
    company: "NutriBest Leeds",
    industry: "Хранителни добавки",
    tagline: "Добавки за отслабване и метаболитна подкрепа.",
    description: "Leeds-based specialist в weight management supplements, metabolic support и healthy lifestyle products за the Yorkshire region.",
    challenge: "Weight loss supplement market е notorious за unrealistic claims и low trust. Нужно беше да differentiate чрез realistic expectations и sustainable approach.",
    solution: "Приложихме transparent communication strategy чрез Trendlab™ focused на realistic weight loss journeys. SEO Struktor™ за evidence-based weight loss content и Clientomat™ за long-term customer support и progress tracking.",
    results: [
      { metric: "+155%", description: "sustainable customer relationships" },
      { metric: "£52,000", description: "месечни продажби (от £24,000)" },
      { metric: "+200%", description: "customer success stories" },
      { metric: "78%", description: "12-month customer retention" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "We're not selling false dreams anymore - we're supporting real transformations.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "wellnesscore-bristol",
    company: "WellnessCore Bristol",
    industry: "Хранителни добавки",
    tagline: "Колаген и анти-ейдж добавки за holistic wellness.",
    description: "Bristol-based wellness company focused на anti-aging supplements, колаген products и holistic health solutions за health-conscious consumers.",
    challenge: "Anti-aging market е saturated с expensive products и questionable claims. Трябваше да establish scientific credibility while remaining accessible.",
    solution: "Развихме science-communication approach чрез Trendlab™ с research-backed content. SEO Struktor™ за anti-aging и wellness keywords, и Clickstarter™ за targeted campaigns към 35+ demographics.",
    results: [
      { metric: "+225%", description: "educated customer base" },
      { metric: "£88,000", description: "месечни продажби (от £32,000)" },
      { metric: "+180%", description: "subscription customers" },
      { metric: "4.7/5", description: "product effectiveness rating" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clickstarter™"],
    testimonial: "Our customers understand the science behind our products. Quality education leads to quality results.",
    image: "/api/placeholder/600/400",
  },
  // FOOD SUPPLEMENTS CATEGORY - FRANCE
  {
    id: "biosupplements-lyon",
    company: "BioSupplements Lyon",
    industry: "Хранителни добавки",
    tagline: "Био добавки от френски продуценти с focus върху terroir quality.",
    description: "Lyon-based дистрибутор на френски bio supplements, capitalizing на France's reputation за quality food products и natural ingredients.",
    challenge: "French market е традиционно conservative относно supplements, preferring natural food sources. Нужно беше да convince consumers на benefits of concentrated supplementation.",
    solution: "Приложихме terroir-based marketing strategy чрез Trendlab™, positioning supplements като extension of French culinary excellence. SEO Struktor™ за 'compléments alimentaires bio' и Clientomat™ за education-focused customer journey.",
    results: [
      { metric: "+165%", description: "French market acceptance" },
      { metric: "€68,000", description: "месечни продажби (от €28,000)" },
      { metric: "+190%", description: "organic product line growth" },
      { metric: "89%", description: "customer preference vs imports" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Nous avons prouvé que les suppléments français peuvent rivaliser avec les meilleurs au monde.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "nutrivie-paris",
    company: "NutriVie Paris",
    industry: "Хранителни добавки",
    tagline: "Луксозни добавки за красота и wellness в сърцето на Париж.",
    description: "High-end Parisian supplement boutique focused на beauty-from-within approach, catering към luxury wellness market в Paris.",
    challenge: "Luxury supplement market изисква exceptional quality и exclusive positioning. Competition от international luxury beauty brands беше intense.",
    solution: "Създадохме exclusive luxury positioning чрез Trendlab™ content focused на Parisian lifestyle. Clickstarter™ за affluent demographics targeting и Clientomat™ за VIP customer experience и personalized beauty consultations.",
    results: [
      { metric: "+280%", description: "luxury customer acquisition" },
      { metric: "€125,000", description: "месечни продажби (от €35,000)" },
      { metric: "+320%", description: "average order value" },
      { metric: "95%", description: "customer retention в luxury segment" },
    ],
    systems: ["Trendlab™", "Clickstarter™", "Clientomat™"],
    testimonial: "Nos clients parisiens reconnaissent enfin la valeur des suppléments de luxe français.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "healthmax-marseille",
    company: "HealthMax Marseille",
    industry: "Хранителни добавки",
    tagline: "Средиземноморски растителни екстракти и натурални добавки.",
    description: "Marseille-based компания specializing в Mediterranean plant extracts, leveraging regional botanical heritage за unique supplement formulations.",
    challenge: "Regional plant extracts нямаха mainstream recognition. Трябваше да educate market за benefits of Mediterranean botanicals vs common supplements.",
    solution: "Разработихме botanical education strategy чрез Trendlab™ highlighting Mediterranean diet benefits. SEO Struktor™ за plant-based supplement searches и Clientomat™ за seasonal botanical recommendations based на traditional usage.",
    results: [
      { metric: "+145%", description: "botanical supplement awareness" },
      { metric: "€58,000", description: "месечни продажби (от €26,000)" },
      { metric: "+175%", description: "export sales to other EU countries" },
      { metric: "4.6/5", description: "product authenticity rating" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "La Méditerranée nous offre les meilleurs ingrédients naturels. Maintenant le monde le sait.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "vitaplus-toulouse",
    company: "VitaPlus Toulouse",
    industry: "Хранителни добавки",
    tagline: "Пробиотици и храносмилателни добавки за digestive wellness.",
    description: "Toulouse-based specialist в digestive health supplements, particularly probiotics, enzyme support и gut health products за the growing wellness market.",
    challenge: "Digestive health е sensitive topic requiring medical credibility. French consumers needed education за микробиом importance и probiotic benefits.",
    solution: "Внедрихме scientific education approach чрез Trendlab™ с gastroenterologist collaborations. SEO Struktor™ за digestive health keywords и Clientomat™ за personalized gut health programs и symptom tracking.",
    results: [
      { metric: "+200%", description: "digestive health awareness" },
      { metric: "€72,000", description: "месечни продажби (от €30,000)" },
      { metric: "+250%", description: "subscription probiotic customers" },
      { metric: "91%", description: "customer symptom improvement reported" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Nos clients comprennent enfin l'importance de la santé intestinale. Les résultats parlent d'eux-mêmes.",
    image: "/api/placeholder/600/400",
  },
  // FOOD SUPPLEMENTS CATEGORY - NETHERLANDS/BELGIUM
  {
    id: "dutchhealth-amsterdam",
    company: "DutchHealth Amsterdam",
    industry: "Хранителни добавки",
    tagline: "Конопени и CBD добавки в liberal Netherlands market.",
    description: "Amsterdam-based company specializing в hemp-derived supplements и CBD wellness products, capitalizing на Netherlands' progressive regulations.",
    challenge: "CBD market беше nисhe и confusing за consumers. Regulatory compliance и consumer education were major challenges в emerging market.",
    solution: "Приложихме education-first approach чрез Trendlab™ с medical cannabis research content. SEO Struktor™ за CBD wellness keywords и Clientomat™ за dosage guidance и compliance tracking.",
    results: [
      { metric: "+380%", description: "CBD market education и adoption" },
      { metric: "€115,000", description: "месечни продажби (от €22,000)" },
      { metric: "+290%", description: "medical professional referrals" },
      { metric: "4.8/5", description: "product quality satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "We've made CBD wellness accessible and trustworthy for Dutch consumers.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "belgianvitamins-brussels",
    company: "BelgianVitamins Brussels",
    industry: "Хранителни добавки",
    tagline: "Европейски сертифицирани добавки с focus върху quality standards.",
    description: "Brussels-based distributor на EU-certified supplements, positioning Belgium като quality gateway между Northern и Southern European markets.",
    challenge: "Belgium's position в EU could be advantage или disadvantage. Трябваше да establish unique identity в crowded European supplement market.",
    solution: "Създадохме EU-quality positioning strategy чрез Trendlab™ highlighting European standards benefits. SEO Struktor™ за multi-language European market coverage и Clickstarter™ за cross-border e-commerce optimization.",
    results: [
      { metric: "+195%", description: "pan-European market recognition" },
      { metric: "€85,000", description: "месечни продажби (от €32,000)" },
      { metric: "+165%", description: "export to neighboring EU countries" },
      { metric: "96%", description: "EU quality standard compliance" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clickstarter™"],
    testimonial: "Belgian quality standards are now recognized across Europe. We're the trusted EU gateway.",
    image: "/api/placeholder/600/400",
  },
  // FOOD SUPPLEMENTS CATEGORY - SCANDINAVIA
  {
    id: "nordicnutrition-stockholm",
    company: "NordicNutrition Stockholm",
    industry: "Хранителни добавки",
    tagline: "Рибено масло и Омега-3 supplements от Nordic pristine waters.",
    description: "Stockholm-based specialist в high-quality fish oil supplements, sourcing от Scandinavian waters известни за purity и sustainability.",
    challenge: "Fish oil market беше commoditized със широк range на quality. Scandinavian sourcing advantage не беше properly communicated to global market.",
    solution: "Разработихме purity и sustainability positioning чрез Trendlab™ с environmental storytelling. SEO Struktor™ за premium fish oil keywords и Clientomat™ за subscription delivery programs emphasizing freshness.",
    results: [
      { metric: "+235%", description: "premium Nordic fish oil recognition" },
      { metric: "€95,000", description: "месечни продажби (от €28,000)" },
      { metric: "+180%", description: "subscription customer base" },
      { metric: "4.9/5", description: "purity и freshness rating" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Nordic purity is our competitive advantage. Customers worldwide recognize our quality.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "healthnord-copenhagen",
    company: "HealthNord Copenhagen",
    industry: "Хранителни добавки",
    tagline: "Витамин D и зимни добавки за Nordic climate wellness.",
    description: "Copenhagen-based company specialized в supplements addressing Nordic climate challenges, particularly Vitamin D deficiency и seasonal wellness support.",
    challenge: "Seasonal supplement needs were underaddressed в mainstream market. Nordic consumers needed targeted solutions за long winters и limited sunlight.",
    solution: "Внедрихме seasonal wellness strategy чрез Trendlab™ focused на Nordic lifestyle adaptation. SEO Struktor™ за seasonal health keywords и Clientomat™ за seasonal subscription programs aligned с climate patterns.",
    results: [
      { metric: "+210%", description: "seasonal wellness awareness" },
      { metric: "€68,000", description: "месечни продажби (от €25,000)" },
      { metric: "+160%", description: "winter supplement subscription rate" },
      { metric: "88%", description: "customer seasonal mood improvement reported" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "We've solved Nordic winter wellness challenges. Our customers feel the difference.",
    image: "/api/placeholder/600/400",
  },
  // FOOD SUPPLEMENTS CATEGORY - BULGARIA & ADDITIONAL INTERNATIONAL
  {
    id: "naturstorebg-sofia",
    company: "NaturStore София",
    industry: "Хранителни добавки",
    tagline: "Водещ магазин за спортни добавки в столицата с focus върху kvalitet.",
    description: "Established магазин в София специализиран в import спортни добавки и натурални продукти за фитнес общността в България.",
    challenge: "България имаше limited awareness за quality supplements. Клиентите купуваха основно по цена без да разбират стойността на премиум продукти.",
    solution: "Внедрихме education-first approach чрез Trendlab™ с local fitness influencer partnerships. SEO Struktor™ за 'спортни добавки София' keywords и Clientomat™ за customer education program и product recommendations.",
    results: [
      { metric: "+320%", description: "образовани клиенти за quality supplements" },
      { metric: "145,000 лв", description: "месечни продажби (от 42,000 лв)" },
      { metric: "+280%", description: "premium product sales" },
      { metric: "87%", description: "customer satisfaction rate" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Конкурентите продават на ниски цени, ние продаваме стойност. Клиентите разбират разликата.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "biohealthpd-plovdiv", 
    company: "Bio Health Store Пловдив",
    industry: "Хранителни добавки",
    tagline: "Био добавки и натурални продукти за здравословен живот в Пловдив.",
    description: "Family-owned health store в Пловдив offering organic supplements, herbal extracts и natural wellness products за local community.",
    challenge: "Пловдивчани са консервативни относно supplements, preferring традиционни методи. Трябваше да bridge gap между традиция и modern supplementation.",
    solution: "Създадохме tradition-meets-science approach чрез Trendlab™ connecting traditional Bulgarian herbs с modern extraction methods. SEO Struktor™ за local health searches и Clientomat™ за gradual customer education program.",
    results: [
      { metric: "+195%", description: "local community trust и adoption" },
      { metric: "68,000 лв", description: "месечни продажби (от 28,000 лв)" },
      { metric: "+150%", description: "repeat customer base" },
      { metric: "4.5/5", description: "community recommendation rating" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Успяхме да обединим традиционните български билки с модерните добавки. Клиентите се чувстват по-здрави.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "fitnessnutrition-varna",
    company: "Fitness Nutrition Варна",
    industry: "Хранителни добавки",
    tagline: "Протеини и креатин за морската столица на България.",
    description: "Specialized fitness supplement shop в Варна catering към expanding fitness scene в Black Sea region.",
    challenge: "Варна fitness scene беше growing but fragmented. Local gyms needed reliable supplement source, но нямаше established vendor relationships.",
    solution: "Приложихме B2B + B2C dual strategy чрез Trendlab™ за fitness community building. SEO Struktor™ за Варна fitness searches, Clickstarter™ за gym partnerships и Clientomat™ за bulk ordering systems.",
    results: [
      { metric: "+175%", description: "gym partnership agreements" },
      { metric: "125,000 лв", description: "месечни продажби (от 45,000 лв)" },
      { metric: "+200%", description: "B2B bulk sales growth" },
      { metric: "78%", description: "Варна gym market penetration" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clickstarter™", "Clientomat™"],
    testimonial: "Станахме официален доставчик на повечето fitness центрове във Варна. Това е признание за качеството ни.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "zdravoslovenbg-burgas",
    company: "Здравословен Живот Бургас",
    industry: "Хранителни добавки",
    tagline: "Витамини и wellness продукти за healthy lifestyle в Бургас.",
    description: "Comprehensive health store в Бургас providing широк range от vitamins, minerals и wellness supplements за diverse customer base.",
    challenge: "Бургас като industrial city имаше limited health consciousness. Residents нуждаха от education за preventive health и supplement benefits.",
    solution: "Внедрихме health education campaign чрез Trendlab™ с local doctors collaborations. SEO Struktor™ за health-related local searches и Clientomat™ за personalized health assessment program.",
    results: [
      { metric: "+160%", description: "health awareness в Бургас community" },
      { metric: "89,000 лв", description: "месечни продажби (от 35,000 лв)" },
      { metric: "+140%", description: "preventive health product sales" },
      { metric: "4.6/5", description: "customer health improvement rating" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Бургазлии започнаха да се грижат превантивно за здравето си. Това променя целия град.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "austrian-supplements-vienna",
    company: "Austrian Supplements Vienna",
    industry: "Хранителни добавки",
    tagline: "Австрийски премиум добавки с Alpine quality standards.",
    description: "Vienna-based premium supplement distributor leveraging Austria's reputation за high-quality health products и Alpine sourcing.",
    challenge: "Austrian supplement market беше dominated от German imports. Local companies struggled да establish unique Austrian identity и premium positioning.",
    solution: "Създадохме Alpine wellness positioning чрез Trendlab™ highlighting Austrian mountain-sourced ingredients. SEO Struktor™ за 'österreichische Nahrungsergänzung' и Clickstarter™ за premium market targeting.",
    results: [
      { metric: "+190%", description: "Austrian premium supplement recognition" },
      { metric: "€92,000", description: "месечни продажби (от €35,000)" },
      { metric: "+165%", description: "export to neighboring countries" },
      { metric: "4.7/5", description: "premium quality satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clickstarter™"],
    testimonial: "Österreichische Qualität ist wieder erkennbar. Unsere Kunden schätzen Alpine Reinheit.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "italian-vitality-milan",
    company: "Italian Vitality Milano",
    industry: "Хранителни добавки",
    tagline: "Италиански wellness добавки с Mediterranean heritage.",
    description: "Milano-based wellness company specializing в Mediterranean diet supplements, olive-derived antioxidants и Italian lifestyle products.",
    challenge: "Italian market предпочиташе food over supplements. Convincing Italians да supplement their already healthy Mediterranean diet беше challenging.",
    solution: "Разработихме Mediterranean enhancement approach чрез Trendlab™ positioning supplements като enhancement, not replacement на traditional diet. SEO Struktor™ за 'integratori mediterranei' и Clientomat™ за seasonal wellness programs.",
    results: [
      { metric: "+145%", description: "acceptance среди traditional Italians" },
      { metric: "€78,000", description: "месечни продажби (от €32,000)" },
      { metric: "+180%", description: "Mediterranean supplement category growth" },
      { metric: "91%", description: "customer lifestyle satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Abbiamo dimostrato che gli integratori possono migliorare la dieta mediterranea, non sostituirla.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "spanish-energia-barcelona",
    company: "Energía Natural Barcelona",
    industry: "Хранителни добавки",
    tagline: "Испански природни енергийни добавки за активен живот.",
    description: "Barcelona-based company focused на natural energy supplements, adaptogens и performance enhancers за active Spanish lifestyle.",
    challenge: "Spanish supplement market беше underdeveloped compared to northern Europe. Local consumers needed education за natural energy alternatives to caffeine dependence.",
    solution: "Внедрихме natural energy education strategy чрез Trendlab™ с Spanish lifestyle integration. SEO Struktor™ за 'suplementos energéticos naturales' и Clickstarter™ за active lifestyle targeting.",
    results: [
      { metric: "+220%", description: "natural energy supplement adoption" },
      { metric: "€85,000", description: "месечни продажби (от €28,000)" },
      { metric: "+175%", description: "adaptogen product line growth" },
      { metric: "4.4/5", description: "sustained energy satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clickstarter™"],
    testimonial: "Los españoles han descubierto la energía natural sostenible. Ya no dependemos tanto del café.",
    image: "/api/placeholder/600/400",
  },
  // ADDITIONAL CATEGORIES TO REACH 47+ TOTAL
  // RESTAURANT CATEGORY ADDITIONS
  {
    id: "bistro-milano-florence",
    company: "Bistro Milano",
    industry: "Ресторантьорство",
    tagline: "Автентичен италиански ресторант във Флоренция със семейни рецепти.",
    description: "Традиционно италианско bistro във Флоренция, предлагащо домашна паста и регионални специалитети в туристически район.",
    challenge: "Туристическата конкуренция във Флоренция е огромна. Ресторантът се бореше да се отличи сред стотиците заведения и да привлече както туристи, така и местни жители.",
    solution: "Внедрихме Trendlab™ стратегия за authentic storytelling, разказваща историята на семейните рецепти. SEO Struktor™ за 'authentic Italian restaurant Florence' и Clientomat™ за reservation system и customer experience tracking.",
    results: [
      { metric: "+185%", description: "резервации от international туристи" },
      { metric: "€125,000", description: "месечни приходи (от €48,000)" },
      { metric: "+140%", description: "местни клиенти vs туристи ratio" },
      { metric: "4.8/5", description: "TripAdvisor rating improvement" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Nonna sarebbe orgogliosa - turisti e locali amano le nostre ricette di famiglia!",
    image: "/api/placeholder/600/400",
  },
  {
    id: "le-petit-cafe-lyon",
    company: "Le Petit Café",
    industry: "Ресторантьорство",
    tagline: "Френска bistro в Лион с focus върху local ingredients.",
    description: "Уютно френско bistro в Lyon, специализирано в традиционна лионска кухня с modern twist и local sourcing.",
    challenge: "Lyon е известен като гастрономическа столица на Франция, което създава изключително високи очаквания и fierce конкуренция от Michelin-starred establishments.",
    solution: "Разработихме local gastronomy positioning чрез Trendlab™ highlighting Lyon's culinary heritage. SEO Struktor™ за 'restaurant traditionnel Lyon' и Clickstarter™ за local food tourism marketing.",
    results: [
      { metric: "+165%", description: "local food enthusiast discovery" },
      { metric: "€95,000", description: "месечни приходи (от €42,000)" },
      { metric: "+120%", description: "food tourism bookings" },
      { metric: "4.6/5", description: "local gastronomy rating" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clickstarter™"],
    testimonial: "Nous avons prouvé qu'un petit bistro peut rivaliser avec les grands restaurants lyonnais.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "old-london-pub",
    company: "The Old London Pub",
    industry: "Ресторантьорство", 
    tagline: "Традиционен английски pub с craft beer selection.",
    description: "Historic London pub специализиран в craft beers, traditional pub food и authentic British dining experience.",
    challenge: "London pub scene е highly competitive със changing consumer preferences toward craft options. Traditional pubs struggle срещу modern gastropubs и cocktail bars.",
    solution: "Внедрихме craft beer expertise positioning чрез Trendlab™ с beer education content. SEO Struktor™ за 'craft beer pub London' и Clientomat™ за beer tasting events и loyalty program.",
    results: [
      { metric: "+200%", description: "craft beer enthusiast regulars" },
      { metric: "£88,000", description: "месечни приходи (от £38,000)" },
      { metric: "+175%", description: "beer tasting event attendance" },
      { metric: "4.5/5", description: "craft beer selection rating" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "We've become London's go-to destination for craft beer education and authentic pub experience.",
    image: "/api/placeholder/600/400",
  },
  // FITNESS CATEGORY ADDITIONS
  {
    id: "powergym-berlin",
    company: "PowerGym Berlin",
    industry: "Фитнес",
    tagline: "Немска фитнес верига в Берлин с focus върху strength training.",
    description: "Modern fitness chain в Berlin специализирана в weightlifting, powerlifting и strength training за serious athletes.",
    challenge: "Berlin fitness market е saturated със budget chains и boutique studios. PowerGym needed да carve out niche за serious strength training enthusiasts.",
    solution: "Създадохме strength training authority positioning чрез Trendlab™ с powerlifting community content. SEO Struktor™ за 'Krafttraining Berlin' и Clientomat™ за advanced training program tracking.",
    results: [
      { metric: "+240%", description: "serious athlete membership" },
      { metric: "€145,000", description: "месечни приходи (от €48,000)" },
      { metric: "+180%", description: "powerlifting competition participants" },
      { metric: "4.7/5", description: "strength training satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Wir sind Berlin's Kraftsport-Hauptquartier geworden. Echte Athleten trainieren hier.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "fitlife-london",
    company: "FitLife London",
    industry: "Фитнес",
    tagline: "Бутикови фитнес студия в London с personalized training approach.",
    description: "Premium boutique fitness studio в London offering personalized training, small group classes и holistic wellness approach.",
    challenge: "London fitness market е oversaturated с premium options. Differentiation и justifying premium pricing срещу budget gym chains беше difficult.",
    solution: "Разработихме personalized wellness positioning чрез Trendlab™ с transformation success stories. SEO Struktor™ за 'personal training London' и Clientomat™ за client progress tracking и retention.",
    results: [
      { metric: "+195%", description: "high-value client acquisition" },
      { metric: "£125,000", description: "месечни приходи (от £42,000)" },
      { metric: "+160%", description: "client transformation success rate" },
      { metric: "4.9/5", description: "personalized service satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "We've proven that personalized fitness delivers results that generic gyms can't match.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "yoga-sanctuary-amsterdam",
    company: "Yoga Sanctuary Amsterdam",
    industry: "Фитнес",
    tagline: "Холистично йога студио в Amsterdam с mindfulness focus.",
    description: "Boutique yoga studio в Amsterdam focused на holistic wellness, meditation и mindfulness practices за busy urban professionals.",
    challenge: "Amsterdam wellness scene е competitive със много yoga options. Studio needed да establish unique identity и build sustainable community.",
    solution: "Внедрихме mindfulness lifestyle positioning чрез Trendlab™ с mental health awareness content. SEO Struktor™ за 'mindfulness yoga Amsterdam' и Clientomat™ за community building program.",
    results: [
      { metric: "+175%", description: "mindful living community growth" },
      { metric: "€75,000", description: "месечни приходи (от €32,000)" },
      { metric: "+150%", description: "corporate wellness partnerships" },
      { metric: "4.8/5", description: "mindfulness practice satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "We've created Amsterdam's most authentic mindfulness community. People find peace here.",
    image: "/api/placeholder/600/400",
  },
  // BEAUTY/COSMETICS CATEGORY ADDITIONS
  {
    id: "beautyzone-vienna",
    company: "BeautyZone Vienna",
    industry: "Козметични услуги",
    tagline: "Козметичен салон във Виена с Austrian precision standards.",
    description: "Premium beauty salon в Vienna offering advanced skincare treatments, anti-aging procedures и luxury beauty services.",
    challenge: "Vienna beauty market е sophisticated със high client expectations. Competition от medical spas и luxury hotels беше intense.",
    solution: "Създадохме Austrian precision beauty positioning чрез Trendlab™ с advanced technique education. SEO Struktor™ за 'Kosmetikstudio Wien' и Clientomat™ за luxury client experience tracking.",
    results: [
      { metric: "+185%", description: "luxury beauty client acquisition" },
      { metric: "€95,000", description: "месечни приходи (от €38,000)" },
      { metric: "+140%", description: "anti-aging treatment bookings" },
      { metric: "4.8/5", description: "luxury service satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Österreichische Präzision in der Schönheitspflege - unsere Kunden sehen und spüren den Unterschied.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "paris-elegance-salon",
    company: "Paris Elegance Salon",
    industry: "Козметични услуги",
    tagline: "Парижки елегантен салон за красота с French style expertise.",
    description: "High-end Parisian beauty salon offering French skincare traditions, luxury treatments и style consultations за discerning clientele.",
    challenge: "Paris beauty standards са legendarily high. Salon needed да meet impossible Parisian expectations while competing срещу established luxury institutions.",
    solution: "Разработихме Parisian elegance authority чрез Trendlab™ с French beauty secret content. SEO Struktor™ за 'salon de beauté Paris' и Clickstarter™ за luxury market targeting.",
    results: [
      { metric: "+210%", description: "Parisian style authority recognition" },
      { metric: "€125,000", description: "месечни приходи (от €45,000)" },
      { metric: "+165%", description: "international client tourism" },
      { metric: "4.9/5", description: "French elegance satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clickstarter™"],
    testimonial: "Nous incarnons l'élégance parisienne authentique. Nos clientes rayonnent de confiance française.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "natural-glow-copenhagen",
    company: "Natural Glow Copenhagen",
    industry: "Козметични услуги",
    tagline: "Скандинавски natural beauty салон с sustainable practices.",
    description: "Copenhagen-based eco-conscious beauty salon specializing в natural treatments, sustainable products и Nordic minimalist approach.",
    challenge: "Nordic beauty market values естественност над glamour. Balancing effectiveness с natural approach и meeting sustainability expectations беше challenging.",
    solution: "Внедрихме Nordic natural beauty positioning чрез Trendlab™ с sustainability education. SEO Struktor™ за 'naturlig skønhed København' и Clientomat™ за eco-conscious client program.",
    results: [
      { metric: "+190%", description: "eco-conscious beauty community" },
      { metric: "€68,000", description: "месечни приходи (от €28,000)" },
      { metric: "+155%", description: "sustainable treatment adoption" },
      { metric: "4.7/5", description: "natural beauty satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Vi har bevist, at naturlig skønhed kan være både effektiv og bæredygtig.",
    image: "/api/placeholder/600/400",
  },
  // SPECIALTY/NICHE CATEGORIES
  {
    id: "swiss-wellness-zurich",
    company: "Swiss Wellness Zurich",
    industry: "Здравеопазване",
    tagline: "Швейцарски wellness център с medical precision approach.",
    description: "Premium wellness center в Zurich combining traditional Swiss health practices с modern medical wellness и preventive healthcare.",
    challenge: "Swiss healthcare standards са extremely high. Center needed да justify premium positioning и compete срещу established medical institutions.",
    solution: "Създадохме Swiss medical wellness authority чрез Trendlab™ с preventive health education. SEO Struktor™ за 'Wellness Zentrum Zürich' и Clientomat™ за comprehensive health tracking.",
    results: [
      { metric: "+165%", description: "preventive healthcare adoption" },
      { metric: "€185,000", description: "месечни приходи (от €68,000)" },
      { metric: "+145%", description: "medical wellness program enrollment" },
      { metric: "4.9/5", description: "Swiss quality satisfaction" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clientomat™"],
    testimonial: "Schweizer Wellness-Präzision ist unser Markenzeichen. Kunden vertrauen unserer medizinischen Kompetenz.",
    image: "/api/placeholder/600/400",
  },
  {
    id: "nordic-spa-oslo",
    company: "Nordic Spa Oslo",
    industry: "СПА услуги",
    tagline: "Скандинавски СПА с traditional Nordic wellness practices.",
    description: "Authentic Nordic spa в Oslo featuring traditional Scandinavian wellness rituals, sauna experiences и cold therapy treatments.",
    challenge: "Spa market в Oslo беше competitive с many generic options. Authenticating traditional Nordic practices и educating international clients беше essential.",
    solution: "Разработихме Nordic wellness heritage positioning чрез Trendlab™ с traditional practice education. SEO Struktor™ за 'nordisk spa Oslo' и Clickstarter™ за wellness tourism targeting.",
    results: [
      { metric: "+200%", description: "Nordic wellness tourism" },
      { metric: "€95,000", description: "месечни приходи (от €35,000)" },
      { metric: "+175%", description: "traditional treatment bookings" },
      { metric: "4.8/5", description: "authentic Nordic experience rating" },
    ],
    systems: ["Trendlab™", "SEO Struktor™", "Clickstarter™"],
    testimonial: "Vi har gjort nordisk velvære tilgjengelig for verden. Tradisjonene lever videre.",
    image: "/api/placeholder/600/400",
  },
];