
import { NextRequest, NextResponse } from 'next/server';

const AIRTABLE_API_KEY = process.env.AIRTABLE_API_KEY;
const AIRTABLE_BASE_ID = process.env.AIRTABLE_BASE_ID;
const AIRTABLE_TABLE_NAME = process.env.AIRTABLE_TABLE_NAME || 'Fast Food';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    console.log('Received request body:', JSON.stringify(body, null, 2));

    // Basic validation
    if (!body.restaurant_name || !body.email || !body.phone) {
      console.error('Missing required fields:', {
        restaurant_name: !!body.restaurant_name,
        email: !!body.email,
        phone: !!body.phone,
        daily_orders: !!body.daily_orders,
        avg_order_value: !!body.avg_order_value
      });
      return NextResponse.json(
        { error: 'Missing required fields', received: Object.keys(body) },
        { status: 400 }
      );
    }

    // Validate environment variables
    if (!AIRTABLE_API_KEY || !AIRTABLE_BASE_ID) {
      console.error('Missing Airtable environment variables:', {
        hasApiKey: !!AIRTABLE_API_KEY,
        hasBaseId: !!AIRTABLE_BASE_ID,
        tableName: AIRTABLE_TABLE_NAME
      });
      return NextResponse.json(
        { error: 'Server configuration error' },
        { status: 500 }
      );
    }

    // Create Airtable record - match exact field names from Airtable
    const airtableData = {
      fields: {
        'Restaurant Name': body.restaurant_name,
        'Daily Orders': body.daily_orders,
        'Average Order Value': body.avg_order_value,
        'Email': body.email,
        'Phone': body.phone,
        'Timestamp': body.timestamp || new Date().toISOString()
        // 'Created' field is auto-generated by Airtable, no need to set it manually
      }
    };

    console.log('GLOVO Calculator submission:', JSON.stringify(airtableData.fields, null, 2));

    // Send to Airtable
    const response = await fetch(`https://api.airtable.com/v0/${AIRTABLE_BASE_ID}/${encodeURIComponent(AIRTABLE_TABLE_NAME)}`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${AIRTABLE_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(airtableData)
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error(`Airtable API error: ${response.status} - ${errorText}`);
      console.error('Request URL:', `https://api.airtable.com/v0/${AIRTABLE_BASE_ID}/${encodeURIComponent(AIRTABLE_TABLE_NAME)}`);
      console.error('Request headers:', {
        'Authorization': `Bearer ${AIRTABLE_API_KEY?.substring(0, 10)}...`,
        'Content-Type': 'application/json'
      });
      console.error('Request body:', JSON.stringify(airtableData, null, 2));
      console.error('Environment check:', {
        hasApiKey: !!AIRTABLE_API_KEY,
        apiKeyLength: AIRTABLE_API_KEY?.length,
        baseId: AIRTABLE_BASE_ID,
        tableName: AIRTABLE_TABLE_NAME
      });
      
      let errorDetails;
      try {
        errorDetails = JSON.parse(errorText);
      } catch {
        errorDetails = errorText;
      }
      
      return NextResponse.json(
        { 
          error: 'Airtable API error',
          details: errorDetails,
          status: response.status,
          debug: {
            url: `https://api.airtable.com/v0/${AIRTABLE_BASE_ID}/${encodeURIComponent(AIRTABLE_TABLE_NAME)}`,
            hasValidAuth: !!AIRTABLE_API_KEY && AIRTABLE_API_KEY.startsWith('pat'),
            sentFields: Object.keys(airtableData.fields)
          }
        },
        { status: response.status }
      );
    }

    const result = await response.json();

    return NextResponse.json({ 
      success: true, 
      message: 'Form submitted successfully to Airtable',
      data: result
    });

  } catch (error) {
    console.error('Error processing GLOVO calculator submission:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
